name: Build PR assets

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    name: Build assets
    strategy:
      matrix:
        include:
          - vsce_target: linux-x64
            npm_config_arch: x64
          - vsce_target: linux-arm64
            npm_config_arch: arm64
          - vsce_target: darwin-x64
            npm_config_arch: x64
          - vsce_target: darwin-arm64
            npm_config_arch: arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Install
        run: npm ci
        env:
          npm_config_arch: ${{ matrix.npm_config_arch }}
      - name: Package extension
        run: npm run vscode:package -- --target=${{ matrix.vsce_target }}
      - name: Upload vsix as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.vsce_target }}
          path: "*.vsix"
