name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check formatting
        run: yarn format:check

      - name: Lint
        run: yarn lint

      - name: Compile
        run: yarn compile

      - name: Run tests
        run: yarn test
